Last error:

python3 PlotPiData.py
Traceback (most recent call last):
        File "PlotPiData.py", line 121, in <module>
        pi_B = ThermoData("DataLog(B).txt")
        File "PlotPiData.py", line 33, in __init__
        self.times = [dateutil.parser.parse(s) for s in self.date_string]
        File "PlotPiData.py", line 33, in <listcomp>
        self.times = [dateutil.parser.parse(s) for s in self.date_string]

        File "/home/madihowa/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse

return DEFAULTPARSER.parse(timestr, **kwargs)
        File "/home/madihowa/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 649, in parse
        raise ParserError("Unknown string format: %s", timestr)
        dateutil.parser._parser.ParserError: Unknown string format: 90.1718604507396308-19-2020 13:56:01
